spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: ${SERVER_PORT:8080}

app:
  auth:
    pending-registration:
      expiration: 30m
      cleanup-cron: "0 0 */12 * * *"
      resend-allowed-before-expiry: 10s
      resend-grace-after-expiry: 10m
  security:
    jwt:
      secret: ${ACCESS_TOKEN_SECRET}
  mail:
    gmail:
      username: ${GMAIL_USERNAME}
      app-password: ${GMAIL_APP_PASSWORD}
      from: ${GMAIL_FROM}
